// Copyright (c) ZeniMax Media Inc.
// Licensed under the GNU General Public License 2.0.
// G:\quake2\baseq2\models/monsters/tank

// This file generated by qdata - Do NOT Modify

enum
{
    // melee frames (0..17)
    FRAME_melee1,
    FRAME_melee2,
    FRAME_melee3,
    FRAME_melee4,
    FRAME_melee5,
    FRAME_melee6,
    FRAME_melee7,
    FRAME_melee8,
    FRAME_melee9,
    FRAME_melee10,
    FRAME_melee11,
    FRAME_melee12,
    FRAME_melee13,
    FRAME_melee14,
    FRAME_melee15,
    FRAME_melee16,
    FRAME_melee17,
    FRAME_melee18,

    // death frames (18..38)
    FRAME_death1,
    FRAME_death2,
    FRAME_death3,
    FRAME_death4,
    FRAME_death5,
    FRAME_death6,
    FRAME_death7,
    FRAME_death8,
    FRAME_death9,
    FRAME_death10,
    FRAME_death11,
    FRAME_death12,
    FRAME_death13,
    FRAME_death14,
    FRAME_death15,
    FRAME_death16,
    FRAME_death17,
    FRAME_death18,
    FRAME_death19,
    FRAME_death20,
    FRAME_death21,

    // stand/run frames (39..56) — run reusa estos frames
    FRAME_stand1,
    FRAME_stand2,
    FRAME_stand3,
    FRAME_stand4,
    FRAME_stand5,
    FRAME_stand6,
    FRAME_stand7,
    FRAME_stand8,
    FRAME_stand9,
    FRAME_stand10,
    FRAME_stand11,
    FRAME_stand12,
    FRAME_stand13,
    FRAME_stand14,
    FRAME_stand15,
    FRAME_stand16,
    FRAME_stand17,
    FRAME_stand18,

    // pain frames (57..65)
    FRAME_pain1,
    FRAME_pain2,
    FRAME_pain3,
    FRAME_pain4,
    FRAME_pain5,
    FRAME_pain6,
    FRAME_pain7,
    FRAME_pain8,
    FRAME_pain9
};


constexpr float MODEL_SCALE = 1.000000f;